### ISSUE TITLE
[feature request] highlight the cut-boost button

### ISSUE THREAD

**Issue by trebmuh** [brummer10/Gx4BandEQ.lv2#2]
When navigating with TAB / SHIFT+TAB, we can see the frequency and the power buttons highlighted when we're on it. That's not the case with the cut-boost buttons. We then are navigating into darkness. It'd be great if they could be highlighted the same way as the others are.

**Comment by brummer10** [comment]
The issue is that they don't have a label to highlight, I may highlight the indicator ring instead to indicate witch controller is active.

**Comment by brummer10** [comment]
Okay, I've pushed a fix for that, highlight now the indicator ring of the active cut/boost control.

**Comment by trebmuh** [comment]
Awesome, it's very good like that.
Thank you very much.
